[package]
name = "flowers"
version = "0.1.0"
edition = "2021"


[profile.dev]
opt-level = 0
debug = true
overflow-checks = true


[dependencies]
image = "0.25"
glam = "0.29"
colorgrad = "0.7"
palette = "0.7"
noise = "0.9"
rand = "0.8"
dyn-clone = "1.0"
